# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_mangoes": "2022-06-01-Introduction.ipynb",
         "train_test_split": "2022-06-01-Introduction.ipynb",
         "X_y_cat": "2022-06-01-Introduction.ipynb",
         "SNV": "2022-06-13-Preprocessing.ipynb",
         "MSC": "2022-06-13-Preprocessing.ipynb",
         "SavGol": "2022-06-13-Preprocessing.ipynb",
         "cross_validate": "2022-06-03-Evaluation.ipynb",
         "evaluate": "2022-06-03-Evaluation.ipynb",
         "TqdmCallback": "2022-06-03-Evaluation.ipynb",
         "Optimiser": "2022-06-03-Evaluation.ipynb",
         "PLSRegression": "7-6-2022-3_pls.ipynb"}

modules = ["scikit_models.py"]

doc_url = "https://huonfraser.github.io/"

git_url = "https://github.com/huonfraser/mangoes_blog_public/tree/master/"

def custom_doc_links(name): return None
